# Generated by Django 4.2.1 on 2023-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=6)),
                ('precio', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
